services:
  - type: web
    name: user_service
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 9020
    healthCheckPath: /actuator/health
    autoDeploy: true