spring:
  application:
    name: USER-SERVICE # Changed to uppercase to match Eureka registration


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid,profile,email


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}

  datasource:
    url: jdbc:postgresql://localhost:5432/Life_flow
    username: postgres
    password: rocky
    driver-class-name: org.postgresql.Driver



  mail:
    host: smtp.gmail.com
    port: 587
    username: rockysheoran72@gmail.com
    password: bebj fono wcrm acwx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            trust: "*"


jwt:
  secretKey: paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823

frontend:
  url: http://localhost:3000
backend:
  url: http://localhost:9020/users

deploy:
  env: development

