spring:
  application:
    name: request_service

  # Logging
  logging:
    level:
      com.project.user_service: DEBUG
      org.springframework: INFO
      org.hibernate: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:Q7CT5spoOjGw6rq9CXeNgJ8FIzpgHizt}

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/Life_flow
    username: postgres
    password: rocky
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Springdoc
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs

# JWT
jwt:
  secretKey: paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823

# Deployment
deploy:
  env: development

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Server
server:
  port: 9040
  servlet:
    context-path: /request

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost