spring:
  application:
    name: REQUEST-SERVICE



  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/Life_flow
    username: postgres
    password: rocky
    driver-class-name: org.postgresql.Driver




# JWT
jwt:
  secretKey: paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823

# Deployment
deploy:
  env: development

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:  # ‚Üê CORRECT! This is at root level
    instance-id: REQUEST-SERVICE:9040
    prefer-ip-address: true
    hostname: localhost