spring:
  application:
    name: REQUEST-SERVICE

  profiles:
    active: dev
  # Logging
  logging:
    level:
      com.project.user_service: DEBUG
      org.springframework: INFO
      org.hibernate: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:Q7CT5spoOjGw6rq9CXeNgJ8FIzpgHizt}


  # JPA
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Springdoc
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info


# Server
server:
  port: 9040
  servlet:
    context-path: /request