spring:
  application:
    name: GEOLOCATION-SERVICE
    profiles:
    active: dev

# Datasource
  datasource:
    url: jdbc:h2:mem:geodb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Logging
logging:
  level:
    com.project.user_service: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

server:
  port: 9050
  servlet:
    context-path: /geolocation

osrm:
  api:
    base-url: http://router.project-osrm.org/route/v1/driving/

# User Service URL
user-service:
  url: http://localhost:9020/users

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: GEOLOCATION-SERVICE:9050
    prefer-ip-address: true
    hostname: localhost