spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true


#    loadbalancer:
#      configurations: health-check
#      eureka:
#        enabled: true # Explicitly enable Eureka for the LoadBalancer

  profiles:
    active: dev

  server:
    port: 8080

jwt:
  secretKey: paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823

management:
  endpoints:
    web:
      exposure:
        include: health,info

#    health:
#      show-details: always
#    gateway:
#      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    enabled: true
    register-with-eureka: true
    healthcheck:
      enabled: true

  instance:
    instance-id: api-gateway:8080
    prefer-ip-address: true

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE  # ‚Üê Change to TRACE for debugging
#    org.springframework.cloud.loadbalancer: DEBUG
#    com.netflix.discovery: DEBUG

user.endpoint: http://localhost:9020/users
